### ISSUE TITLE
Pretrained model - Missing files

### ISSUE THREAD

**Issue by CarlosDominguezBecerril** [jcyk/AMR-gs#10]
Hi Deng,

I'm trying to use the pretrained model but it seems to be missing the files of "data/AMR/amr_2.0_utils/". Could you please update the repository with these files?

Thanks

Kind regards,

Carlos

**Comment by jcyk** [comment]
Hi Carlos,

please use `sh download_artifacts.sh` for getting those files. Sorry for did not mention it earlier.


Best,
Deng
