### ISSUE TITLE
Error when loading Bert

### ISSUE THREAD

**Issue by chenllliang** [jcyk/AMR-gs#11]
Hello Deng, thank you for your great work, I met some trouble when trying to use the pretrain model to parse my own text file.

I first run `sh preprocess_raw.sh sample.txt` , where there is only one sentence in sample.txt.

second, I change the scripts work.sh as follows:
`python3 -u -m parser.work --test_data sample.txt.raw.features.preproc \
               --test_batch_size 1 \
               --load_path /home/lchen/AMR-gs/amr2.0.bert.gr/ckpt.pt \
               --beam_size 8\
               --alpha 0.6\
               --max_time_step 100\
               --output_suffix _test_out`

and I get following messages

`Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lchen/AMR-gs/parser/work.py", line 115, in <module>
    bert_tokenizer = BertEncoderTokenizer.from_pretrained(model_args.bert_path, do_lower_case=False)
  File "/home/lchen/AMR-gs/amr/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 282, in from_pretrained
    return cls._from_pretrained(*inputs, **kwargs)
  File "/home/lchen/AMR-gs/amr/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 346, in _from_pretrained
    list(cls.vocab_files_names.values())))
OSError: Model name '../bert-base-cased' was not found in tokenizers model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc, bert-base-german-dbmdz-cased, bert-base-german-dbmdz-uncased). We assumed '../bert-base-cased' was a path or url to a directory containing vocabulary files named ['vocab.txt'] but couldn't find such vocabulary files at this path or url.
`

Is there anything wrong about my procedure ?
Thanks a lot

**Comment by jcyk** [comment]
Hi,

We use transformers to load pretrained Bert and assume the Bert is place at
“../bert-base-cased”.

Hope it help.

**Comment by chenllliang** [comment]
Thank you, it works. however I get another error when executing `sh work.sh`



```
read from sample.txt.raw.features.preproc, 5 amrs
Get 5 AMRs from sample.txt.raw.features.preproc
/home/lchen/AMR-gs/amr2.0.bert.gr/ckpt.pt
Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lchen/AMR-gs/parser/work.py", line 136, in <module>
    batch = int(re.search(r'batch([0-9])+', test_model)[0][5:])
TypeError: 'NoneType' object is not subscriptable
```
There are 5 lines in sample.txt.

Thanks again for your patience

**Comment by jcyk** [comment]
Hi,
Sorry for that the code is not very clean. You can just delete line 136 and line 137. I will update the code.
