### ISSUE TITLE
Trouble parsing with a pre-trained model

### ISSUE THREAD

**Issue by kawu** [jcyk/AMR-gs#12]
Hello Deng, first of all thanks for great work!

I'm trying to use your parser to process a simple input file with the pre-trained `amr2.0.bert.gr`model.  I followed the steps described in the [AMR Parsing with Pretrained Models](https://github.com/jcyk/AMR-gs#amr-parsing-with-pretrained-models) section up to step 3, where I get the following error:
```
$ python -u -m parser.work --test_data test/input.txt.raw.features.preproc --load_path test/amr2.0.bert.gr/ckpt.pt --output_suffix _test_out
To use data.metrics please install scikit-learn. See https://scikit-learn.org/stable/index.html
Traceback (most recent call last):
  File "/home/waszczuk/.conda/envs/amrgs/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/waszczuk/.conda/envs/amrgs/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/waszczuk/work/github/other/AMR-gs/parser/work.py", line 101, in <module>
    vocabs['tok'] = Vocab(model_args.tok_vocab, 5, [CLS])
  File "/home/waszczuk/work/github/other/AMR-gs/parser/data.py", line 17, in __init__
    for line in open(filename).readlines():
FileNotFoundError: [Errno 2] No such file or directory: '../data/AMR/amr_2.0_reca/tok_vocab'
```
Am I doing something wrong?  Maybe the argument I provide for the `load_path` parameter is not correct?

**Comment by jcyk** [comment]
Hi @kawu  Thanks for your interest!

Due to historic reasons, The program searchs for vocab files in prescribed path `../data/AMR/amr_2.0_reca`. One workaround is  `mkdir ../data/AMR/amr_2.0_reca` and then put all vocab files in this folder. (The vocab files can be found in decompressed amr2.0.bert.gr.tar.gz).

**Comment by kawu** [comment]
This fixed the issue, thanks a lot!
