### ISSUE TITLE
The files of pretained models have been unavilable

### ISSUE THREAD

**Issue by ntu-zjy** [jcyk/AMR-gs#22]
https://drive.google.com/file/d/1v1fEoJGIrpM6kRzY796nDy2Ju6eFLs9-/view?usp=drive_open
https://drive.google.com/file/d/1S-P6Y6c-_5-uzcqyX7-BixVUvFzN0MG9/view?usp=sharing
These links could not be open.

**Comment by jcyk** [comment]
Hi I retied but these links are fine.
could you please try again.

**Comment by ntu-zjy** [comment]
wow, thank you very much!



---Original---
From: "Deng ***@***.***&gt;
Date: Sat, Oct 22, 2022 20:56 PM
To: ***@***.***&gt;;
Cc: "Jingyuan ***@***.******@***.***&gt;;
Subject: Re: [jcyk/AMR-gs] The files of pretained models have been unavilable(Issue #22)




 
Closed #22 as completed.
