### ISSUE TITLE
Cannot load pre-trained model 

### ISSUE THREAD

**Issue by flipz357** [jcyk/AMR-gs#4]
Hi Deng,

thanks for the awesome work. I am interested in parsing arbitrary sentence. I took your advice with appending the sentences with dummy-AMRs to the test. The preprocessing worked fine so far, however, when I want to apply the pre-trained model to predict using work.sh (with adapted file path for pre-trained model), I get the following error:

  File "/xxxxx/AMR-gs/parser/work.py", line 94, in <module>
    model_args = torch.load(fname)['args']
....
  File "/zzzzzr/lib/python3.6/site-packages/torch/serialization.py", line 563, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x00'

The path in work.sh looks as follows:

--load_path amr2.0.bert.gr \

Previously I had downloaded your pre-trained model in the main directory and used tar -xvzf to extract. Did I make any error in the extraction process? My amr2.0.bert.gr contains a file "ckpt.pt" and a directory "vocabs".

**Comment by jcyk** [comment]
the --load_path should only point to the ckpt.pt file, not the whole directory. The vocab files should be placed to the directory specified by `model_args`, see https://github.com/jcyk/AMR-gs/blob/b9c0043d3a885de15556a7d9b9d348389c1b96b4/parser/work.py#L101-L109

I am sorry for this inconvenience.

**Comment by flipz357** [comment]
Thanks, Deng, it works now!

**Comment by jcyk** [comment]
@fliegenpilz357 
Hi, it seems you did not do the postprocessing step ?!

**Comment by jcyk** [comment]
It seems to me that the result is good, except for that you did not do the post-processing step so the result is incomplete. please let me know your point so I can help --). @fliegenpilz357

**Comment by flipz357** [comment]
Oh, stupid me! This is completely right, I did not run the post processing. Thank you for your patience and the quick answers!
