### ISSUE TITLE
Final output files of the models

### ISSUE THREAD

**Issue by RikVN** [jcyk/AMR-gs#7]
Hi Deng,

first of all, great work. I wondered if you could share your "official" output files that scores 78.7 and 80.2 on the test set. I'd like to do some analysis regarding other AMR metrics (SemBleu, s2match), and perhaps performance over sentence length.

If possible, I'd also like the test output of your model in the "core semantic first" paper, that scored 73.2

Thanks a lot! Rik

**Comment by jcyk** [comment]
Hi, @RikVN. Thanks! Could you leave your mail address? 
I will send to you soon.

**Comment by RikVN** [comment]
Great! rikvannoord [at] gmail.com

**Comment by jcyk** [comment]
sent
