### ISSUE TITLE
.features file not found when running preprocess_raw.sh

### ISSUE THREAD

**Issue by esmanning** [jcyk/AMR-gs#8]
I'm trying to parse raw sentences with a pretrained model. The file has one sentence per line as expected and I am running the Stanford CoreNLP server.

When I try to run

sh preprocess_raw.sh my_filename.txt

it successfully creates my_filename.txt.raw, as well as an empty file called my_filename.txt.raw.features.input_clean, but then throws an error:
FileNotFoundError: [Errno 2] No such file or directory: 'data/AMR/amr_2.0/my_filename.txt.raw.features'

I'm not sure where the .features file is supposed to come from - am I missing a preprocessing step?

I thought maybe I needed to run annotate_features.sh, but that seems to expect a full directory structure with train/dev/test split, and I just want to run a pretrained model on a file of test sentences.

**Comment by esmanning** [comment]
It seems these lines needed to be uncommented in preprocess_raw.sh:

python -u -m stog.data.dataset_readers.amr_parsing.preprocess.feature_annotator \
     ${raw_file}.raw \
     --compound_file ${compound_file}

**Comment by jcyk** [comment]
oops! yes you are right. I will uncommented these lines
